version: '3.3'
services:
  server:
    build: .
    container_name: app-server
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:15432/cxa_dev
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  db:
    image: postgres:12
    container_name: app-db
    volumes:
      - db-data:/var/lib/postgresql
    expose:
      - 15432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cxa_dev
      - PGPORT=15432
volumes:
  db-data:
